model_type: harmony

architecture:
  input_length: 8
  dropout_rate: 0.4
  embedding_dimension: 24
  gru_size: 256
  dense_size: 128
  gru_dropout_rate: 0.3

compile_info:
  optimizer: Adam
  loss:
    harmony: SparseCategoricalCrossentropy
    duration: SparseCategoricalCrossentropy
  save_architecture_summary: True
  save_architecture_image: True

training:
  epochs: 40
  validation_split: 0.2
  save_weights: True

callbacks:
  ReduceLROnPlateau:
    monitor: output_1_sparse_categorical_accuracy
    patience: 7
    factor: 0.3
    min_lr: 5e-5
  EarlyStopping:
    monitor: output_1_sparse_categorical_accuracy
    patience: 10
    restore_best_weights: True
